;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Input.Jump",NewTagName="Input.Dodge")
+GameplayTagRedirects=(OldTagName="CCTags.Attack.amageWindow",NewTagName="CCTags.Attack.DamageWindow")
+GameplayTagRedirects=(OldTagName="CCTags.Attack.Active",NewTagName="CCTags.Attack.Attacking")
+GameplayTagRedirects=(OldTagName="CCTags.Attack.ComboWindow",NewTagName="CCTags.Attack.WindowOpen")
+GameplayTagRedirects=(OldTagName="CCTags.Attack.InputBuffered",NewTagName="CCTags.Attack.InputQueued")
+GameplayTagRedirects=(OldTagName="CCTags.Event.StartAttack",NewTagName="CCTags.Event.Move")
+GameplayTagRedirects=(OldTagName="CCTags.Attacking.Combo01",NewTagName="CCTags.Attacking.ComboStart")
+GameplayTagRedirects=(OldTagName="CCTags.Attacking.ComboEnd",NewTagName="CCTags.Attacking.AttackEnd")
+GameplayTagRedirects=(OldTagName="CCTags.Attacking.ComboStart",NewTagName="CCTags.Attacking.AttackStart")
+GameplayTagRedirects=(OldTagName="CCTags.Event.Move",NewTagName="CCTags.Event.MoveInput")
+GameplayTagRedirects=(OldTagName="CCTags.Attacking.Combo02",NewTagName="CCTags.Attacking.Comboing")
+GameplayTagRedirects=(OldTagName="CCTags.CCAbilities.Respaw",NewTagName="CCTags.CCAbilities.Respawn")
+GameplayTagList=(Tag="CCTags.Attack.Attacking",DevComment="")
+GameplayTagList=(Tag="CCTags.Attack.InputQueued",DevComment="")
+GameplayTagList=(Tag="CCTags.Attack.ReAttacking",DevComment="")
+GameplayTagList=(Tag="CCTags.Attack.WindowOpen",DevComment="")
+GameplayTagList=(Tag="CCTags.Attacking",DevComment="")
+GameplayTagList=(Tag="CCTags.Attacking.AttackEnd",DevComment="")
+GameplayTagList=(Tag="CCTags.Attacking.AttackStart",DevComment="")
+GameplayTagList=(Tag="CCTags.Attacking.ComboCheck",DevComment="")
+GameplayTagList=(Tag="CCTags.Attacking.Comboing",DevComment="")
+GameplayTagList=(Tag="CCTags.CCAbilities.Death",DevComment="")
+GameplayTagList=(Tag="CCTags.CCAbilities.FindActor",DevComment="")
+GameplayTagList=(Tag="CCTags.CCAbilities.Respawn",DevComment="")
+GameplayTagList=(Tag="CCTags.Event.Attack",DevComment="")
+GameplayTagList=(Tag="CCTags.Event.AttackInput",DevComment="")
+GameplayTagList=(Tag="CCTags.Event.BeHit",DevComment="")
+GameplayTagList=(Tag="CCTags.Event.CanMoveInput",DevComment="")
+GameplayTagList=(Tag="CCTags.Event.LevelUp",DevComment="")
+GameplayTagList=(Tag="CCTags.Event.MoveInput",DevComment="")
+GameplayTagList=(Tag="CCTags.Event.ComboFinished",DevComment="")
+GameplayTagList=(Tag="CCTags.Input",DevComment="")
+GameplayTagList=(Tag="CCTags.Status.Dead",DevComment="")
+GameplayTagList=(Tag="CCTags.Status.SuperArmor",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitReact",DevComment="")
+GameplayTagList=(Tag="Input.Attack",DevComment="")
+GameplayTagList=(Tag="Input.Dodge",DevComment="")
+GameplayTagList=(Tag="Input.Move",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="Lyra CommonUI gameplay layer")
+GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="Lyra CommonUI in-game menu layer")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="Lyra CommonUI frontend layer")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="Lyra CommonUI modal layer")

